### ISSUE TITLE
template

### ISSUE THREAD

**Issue by pascal-canuel** [hacdias/hacdias.com#6]
I think that your website is awesome and minimalist. I would be interested to use it as a template for mine and I'm interested on how you deploy it. 😃 🤔

**Comment by hacdias** [comment]
@pascal-canuel hello! Sorry, only saw this now. I can see you already made it work for your website. Do you still need any further help?

**Comment by pascal-canuel** [comment]
no its good! I made it searching through the commits ahaha. Thanks for your answer, its really appreciated

**Comment by hacdias** [comment]
I'm closing this then!
